import type { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || 'https://buildwithai.digital').replace(/\/$/, '')
  const now = new Date()

  const routes = [
    '/',
    '/about',
    '/academy',
    '/admin/dashboard',
    '/admin/errors',
    '/admin/leads',
    '/admin/payouts',
    '/affiliate',
    '/dashboard',
    '/dashboard/api',
    '/dashboard/billing',
    '/dashboard/infrastructure',
    '/dashboard/mission-control',
    '/developers',
    '/hero-demo',
    '/identity',
    '/leads',
    '/login',
    '/membership',
    '/partners',
    '/partners/dashboard',
    '/privacy',
    '/products',
    '/products/dns/hosting',
    '/products/dns/nameservers',
    '/products/dns/templates',
    '/products/domains/registration',
    '/products/domains/renewal',
    '/products/domains/transfer',
    '/products/easy-dmarc',
    '/products/email/templates',
    '/products/email/verification',
    '/products/licenses/plesk',
    '/products/licenses/virtuozzo',
    '/products/premium-dns',
    '/products/spam-experts',
    '/products/spam-experts/archiving',
    '/products/spam-experts/incoming',
    '/products/spam-experts/outgoing',
    '/products/ssl',
    '/products/ssl/code-signing',
    '/products/ssl/domain-validation',
    '/products/ssl/email-signing',
    '/products/ssl/extended-validation',
    '/products/ssl/multi-domain',
    '/products/ssl/organization-validation',
    '/products/ssl/wildcard',
    '/products/templates',
    '/products/tlds',
    '/services',
    '/services/ai-design',
    '/services/customer-management',
    '/services/domain-management',
    '/services/ssl-management',
    '/signup',
    '/ssl',
    '/terms',
    '/tools/ai-generator',
  ]

  return routes.map((path) => ({
    url: `${siteUrl}${path}`,
    lastModified: now,
    changeFrequency: 'weekly',
    priority: path === '/' ? 1.0 : path.split('/').filter(Boolean).length === 1 ? 0.8 : 0.5,
  }))
}
